### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by zskzsk92** [zskzsk92/furima-38721#19]
# URL
https://furima-38721.onrender.com

# Basic認証
admin
aaa111

# 出品者用のメールアドレスとパスワード
taro@exmple.com
aaa111

# 購入者用のメールアドレスとパスワード
hanako@exmple.com
aaa111

**Comment by snkw-works** [comment]
@zskzsk92 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **クレジットカード決済ができるよう修正しましょう**
現状、以下の正しい情報を入力しても「Token can't be blank」というエラーになってしまい、購入が完了できない状態です。

```
・カード番号：4242424242424242
・CVC：123
・23/12
```

購入機能と購入後に関する項目に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら、以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by zskzsk92** [comment]
お疲れ様です。
ライフコーチより共有いただきました下記カリキュラムを元にPAY. JPをv1からv2に修正しておりますが、ラベル等が一部不要だったためカリキュラムと異なる部分があります。
ご確認よろしくお願いいたします。
https://master.tech-camp.in/v2/curriculums/5526

**Comment by snkw-works** [comment]
@zskzsk92 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（**LGTM**）とさせていただきます。おめでとうございます。

この度は購入機能の実装についてご不便をおかけし、大変申し訳ございませんでした。
引き続き、スタッフ一同精一杯サポートいたしますので、何卒よろしくお願い申し上げます。

【補足】
購入画面のクレジットカード番号入力欄（枠）が表示されない状態です。入力はできるため購入機能としては問題ありませんが、可能であれば見本アプリと同じように入力欄が表示されるよう修正しましょう。必須要件ではないため、修正後のご連絡は不要です。
<img width="932" alt="スクリーンショット 2023-01-09 9 45 26" src="https://user-images.githubusercontent.com/54050089/211227435-d1c9ff6f-5bea-462b-8c99-30a20e32123c.png">
![スクリーンショット_2023-01-09_9_53_57](https://user-images.githubusercontent.com/54050089/211227502-6d96f2a8-6cba-41dd-a730-1da6ae2509e3.jpg)


`本メッセージ内で、今後の学習についてご案内しています。必ず確認するようにしてください。`

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

------------------------------------------------------------------------------------------
◆ 今後の流れについてのご案内（※詳細は下記リンクのガイダンス資料参照）
------------------------------------------------------------------------------------------
◎この後の期間では、以下のアクションが必要となります。
・最終課題説明文の作成・提出
・FURIMAへの追加機能の実装 または オリジナルアプリ開発
・上記の開発に関する要件定義書の提出
・履歴書と職務経歴書の作成・提出（転職サポートありの方）
・学習成果発表会の準備

◎下記リンク先の「**追加実装・オリジナルアプリ開発 ガイダンス資料**」を必ずご確認ください。
**https://master.tech-camp.in/v2/curriculums/7839**

------------------------------------------------------------------------------------------
◆ さいごに
------------------------------------------------------------------------------------------
◎ガイダンス資料を確認した上で、今後の流れについて不明点がございましたら、担当ライフコーチまでご相談ください。

◎いよいよ卒業までのラストスパートです。これまで頑張ってきたことをフル活用して、最大限の受講成果につなげていきましょう。

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
